ngay8/Controllers/DragController.cs
using Microsoft.AspNetCore.Mvc;
using ngay8.Data;
using static ngay8.Controllers.AutoCompleteController;

namespace ngay8.Controllers
{
    public class DragController : Controller
    {
        public static List<CountryJson> GetCountries()
        {
            return new List<CountryJson>() {
                new CountryJson(){id= 1, name = "Afghanistan"},
                new CountryJson(){id= 2, name = "Albania"},
                new CountryJson(){id= 3, name = "Algeria"},
                new CountryJson(){id= 4, name = "Andorra"},
                new CountryJson(){id= 5, name = "Angola"},
                new CountryJson(){id= 6, name = "Anguilla"},
            };
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult TestText()
        {
            var data = GetCountries();

            return PartialView("~/Views/Drag/_ModalTestDrag.cshtml",data);
        }
    }
}

ngay8/Controllers/FileController.cs
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Syncfusion.EJ2.FileManager.Base;
using Syncfusion.EJ2.FileManager.PhysicalFileProvider;

namespace ngay8.Controllers
{
    public class FileController : Controller
    {
        public PhysicalFileProvider operation;
        public string basePath;
        string root = "wwwroot\\Files";
        public FileController(IHostEnvironment hostingEnvironment)
        {
            this.basePath = hostingEnvironment.ContentRootPath;
            this.operation = new PhysicalFileProvider();
            this.operation.RootFolder(this.basePath + "\\" + this.root);
        }

        public object FileOperations([FromBody] FileManagerDirectoryContent args)
        {
            var fullPath = (this.basePath + "\\" + this.root + args.Path).Replace("/", "\\");
            if (args.Action == "delete" || args.Action == "rename")
            {
                if ((args.TargetPath == null) && (args.Path == ""))
                {
                    FileManagerResponse response = new FileManagerResponse();
                    response.Error = new ErrorDetails { Code = "401", Message = "Restricted to modify the root folder." };
                    return this.operation.ToCamelCase(response);
                }
            }
            switch (args.Action)
            {
                case "read":
                    // reads the file(s) or folder(s) from the given path.
                    return this.operation.ToCamelCase(this.operation.GetFiles(args.Path, args.ShowHiddenItems));
                case "delete":
                    // deletes the selected file(s) or folder(s) from the given path.
                    return this.operation.ToCamelCase(this.operation.Delete(args.Path, args.Names));
                case "copy":
                    // copies the selected file(s) or folder(s) from a path and then pastes them into a given target path.
                    return this.operation.ToCamelCase(this.operation.Copy(args.Path, args.TargetPath, args.Names, args.RenameFiles, args.TargetData));
                case "move":
                    // cuts the selected file(s) or folder(s) from a path and then pastes them into a given target path.
                    return this.operation.ToCamelCase(this.operation.Move(args.Path, args.TargetPath, args.Names, args.RenameFiles, args.TargetData));
                case "details":
                    // gets the details of the selected file(s) or folder(s).
                    return this.operation.ToCamelCase(this.operation.Details(args.Path, args.Names, args.Data));
                case "create":
                    // creates a new folder in a given path.
                    return this.operation.ToCamelCase(this.operation.Create(args.Path, args.Name));
                case "search":
                    // gets the list of file(s) or folder(s) from a given path based on the searched key string.
                    return this.operation.ToCamelCase(this.operation.Search(args.Path, args.SearchString, args.ShowHiddenItems, args.CaseSensitive));
                case "rename":
                    // renames a file or folder.
                    return this.operation.ToCamelCase(this.operation.Rename(args.Path, args.Name, args.NewName));
            }
            return null;
        }

        // uploads the file(s) into a specified path
        public IActionResult Upload(string path, IList<IFormFile> uploadFiles, string action)
        {
            FileManagerResponse uploadResponse;
            uploadResponse = operation.Upload(path, uploadFiles, action, null);
            if (uploadResponse.Error != null)
            {
                Response.Clear();
                Response.ContentType = "application/json; charset=utf-8";
                Response.StatusCode = Convert.ToInt32(uploadResponse.Error.Code);
                Response.HttpContext.Features.Get<IHttpResponseFeature>().ReasonPhrase = uploadResponse.Error.Message;
            }
            return Content("");
        }

        // downloads the selected file(s) and folder(s)
        public IActionResult Download(string downloadInput)
        {
            FileManagerDirectoryContent args = JsonConvert.DeserializeObject<FileManagerDirectoryContent>(downloadInput);
            return operation.Download(args.Path, args.Names, args.Data);
        }

        // gets the image(s) from the given path
        public IActionResult GetImage(FileManagerDirectoryContent args)
        {
            return this.operation.GetImage(args.Path, args.Id, false, null, null);
        }
        public IActionResult Index()
        {
            return View();
        }


    }
}

ngay8/Controllers/GraphController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using ngay8.Helper;
using ngay8.Models;
using ngay8.ViewModels;
using Service.Application.GraphDataFeature.Queries;
using Service.Domain.Models;
using static Service.Application.GraphDataFeature.Queries.GetGraphWithStoreProcedure;

namespace ngay8.Controllers
{
    public class GraphController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;
        private readonly AestrainingContext _context;
        private readonly IUriService _uriService;
        public GraphController(IMapper mapper, IMediator mediator, AestrainingContext context, IUriService uriService)
        {
            _mediator = mediator;
            _mapper = mapper;
            _context = context;
            _uriService = uriService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Analytics()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Report(SearchVM search)
        {
            if (!ModelState.IsValid) return Json(new { status = "fail" });
            var getGraphRequest = new GetGraphRequest()
            {
                op = search.op,
                AgentName = search.AgentName,
                AgentCEANO = search.AgentCEANO,
                From = search.From.Value + new TimeSpan(00, 00, 02),
                To = search.To.Value + new TimeSpan(23, 59, 59),
            };

            var resSearch = await _mediator.Send(getGraphRequest);
            var graphData = _mapper.Map<List<GraphData>>(resSearch.ToList());

            var dataCol = graphData.GroupBy(x => new { x.Month, x.Year }).Select(a => new GraphData
            {
                Month = a.Key.Month,
                Year = a.Key.Year,
                GrossValue = Math.Round(a.Sum(b => b.GrossValue), 0),
                NetValue = Math.Round(a.Sum(c => c.NetValue), 0)
            }).ToList();

            if (dataCol == null || dataCol.Count() == 0) return Json(new { status = "fail" });
            return Json(new { status = "success", data = dataCol });
        }
        [HttpPost]
        public async Task<JsonResult> ReportProcedure(SearchVM search)
        {
            if (!ModelState.IsValid) return Json(new { status = "fail" });
            var getGraphRequest = new GetGraphWithStoreProcedureRequest()
            {
                op = search.op,
                AgentName = search.AgentName ?? "",
                AgentCEANO = search.AgentCEANO ?? "",
                From = search.From.Value + new TimeSpan(00, 00, 02),
                To = search.To.Value + new TimeSpan(23, 59, 59),
            };

            var graphDataPro = await _mediator.Send(getGraphRequest);

            if (graphDataPro == null) return Json(new { status = "fail" });
            var dataCol = graphDataPro.GroupBy(x => new { x.Month, x.Year })
                .Select(a => new GraphDataPro
                {
                    Month = a.Key.Month,
                    Year = a.Key.Year,
                    GrossValue = Math.Round(a.Sum(b => b.GrossValue), 0),
                    NetValue = Math.Round(a.Sum(c => c.NetValue), 0)
                }).ToList();

            if (dataCol == null || dataCol.Count() == 0) return Json(new { status = "fail" });
            return Json(new { status = "success", data = dataCol });
        }


        public IActionResult Report()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ExportExcel([FromBody] ClosexmlVM closeXml)
        {
            if (!ModelState.IsValid) return Json(new { status = "fail" });
            var getExcelwithDate = new GetExcelwithDate()
            {
                From = closeXml.From.Value + new TimeSpan(00, 00, 02),
                To = closeXml.To.Value + new TimeSpan(23, 59, 59),
            };
            var top10KeyInDate = await _mediator.Send(getExcelwithDate);
            var exportbyte = top10KeyInDate.ExporttoExcelCloseXML(getExcelwithDate);
            return File(exportbyte, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        }
    }
}

ngay8/Controllers/RateController.cs
using Microsoft.AspNetCore.Mvc;

namespace ngay8.Controllers
{
    public class RateController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Moodal()
        {
            return PartialView("~/Views/Rate/Partial/_RatePartial.cshtml");
        }
    }
}

ngay8/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ngay8</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/graph.css" rel="stylesheet" />
    <link href="~/css/dropdownmenu.css" rel="stylesheet" />

    <script src="https://cdn.tailwindcss.com"></script>


    <!-- file manager and its dependent theme -->
    <link href="https://cdn.syncfusion.com/ej2/21.1.35/ej2-base/styles/material.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.syncfusion.com/ej2/21.1.35/ej2-inputs/styles/material.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.syncfusion.com/ej2/21.1.35/ej2-popups/styles/material.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.syncfusion.com/ej2/21.1.35/ej2-buttons/styles/material.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.syncfusion.com/ej2/21.1.35/ej2-splitbuttons/styles/material.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.syncfusion.com/ej2/21.1.35/ej2-layouts/styles/material.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.syncfusion.com/ej2/21.1.35/ej2-navigations/styles/material.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.syncfusion.com/ej2/21.1.35/ej2-grids/styles/material.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.syncfusion.com/ej2/21.1.35/ej2-filemanager/styles/material.css" rel="stylesheet" type="text/css" />
    <!-- Essential JS 2 file manager's global script -->
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/ej2-base/dist/global/ej2-base.min.js" type="text/javascript"></script>
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/ej2-layouts/dist/global/ej2-layouts.min.js" type="text/javascript"></script>
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/ej2-buttons/dist/global/ej2-buttons.min.js" type="text/javascript"></script>
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/ej2-popups/dist/global/ej2-popups.min.js" type="text/javascript"></script>
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/ej2-data/dist/global/ej2-data.min.js" type="text/javascript"></script>
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/ej2-inputs/dist/global/ej2-inputs.min.js" type="text/javascript"></script>
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/ej2-lists/dist/global/ej2-lists.min.js" type="text/javascript"></script>
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/ej2-dropdowns/dist/global/ej2-dropdowns.min.js" type="text/javascript"></script>
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/ej2-splitbuttons/dist/global/ej2-splitbuttons.min.js" type="text/javascript"></script>
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/ej2-navigations/dist/global/ej2-navigations.min.js" type="text/javascript"></script>
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/ej2-grids/dist/global/ej2-grids.min.js" type="text/javascript"></script>
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/ej2-filemanager/dist/global/ej2-filemanager.min.js" type="text/javascript"></script>

    <!--noti thông báo-->
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.3/dist/sweetalert2.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.3/dist/sweetalert2.all.min.js"></script>

    <!--MultiSelect-->
    <link href="~/js/multiselect/jquery.multiselect.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


    <!--Kanban-->
    <link href="//cdn.syncfusion.com/ej2/21.1.35/ej2-base/styles/material.css" rel="stylesheet">
    <link href="//cdn.syncfusion.com/ej2/21.1.35/ej2-buttons/styles/material.css" rel="stylesheet">
    <link href="//cdn.syncfusion.com/ej2/21.1.35/ej2-inputs/styles/material.css" rel="stylesheet">
    <link href="//cdn.syncfusion.com/ej2/21.1.35/ej2-dropdowns/styles/material.css" rel="stylesheet">
    <link href="//cdn.syncfusion.com/ej2/21.1.35/ej2-layouts/styles/material.css" rel="stylesheet">
    <link href="//cdn.syncfusion.com/ej2/21.1.35/ej2-navigations/styles/material.css" rel="stylesheet">
    <link href="//cdn.syncfusion.com/ej2/21.1.35/ej2-popups/styles/material.css" rel="stylesheet">
    <link href="//cdn.syncfusion.com/ej2/21.1.35/ej2-kanban/styles/material.css" rel="stylesheet">
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/dist/ej2.min.js" type="text/javascript"></script>


    <!--Pond File-->
    <link rel="stylesheet"
          href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css">
    <link rel="stylesheet" href="https://unpkg.com/filepond/dist/filepond.min.css">

    <script src="https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.min.js"></script>
    <script src="https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.min.js"></script>
    <script src="https://unpkg.com/filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.min.js"></script>
    <script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.js"></script>
    <script src="https://unpkg.com/filepond/dist/filepond.min.js"></script>

    <!--summer note-->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

</head>

<body>
    <header style="margin-top:100px">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ngay8</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TransData" asp-action="Index">Search</a>
                        </li>
                        <li class="drop-holder">
                            <div class="dropdown">
                                <a class="nav-link text-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    Report and analytics
                                </a>
                                <ul class="dropdown-menu " aria-labelledby="dropdownMenuLink">
                                    <li><a class="dropdown-item text-dark" asp-controller="Graph" asp-action="Report">Report</a></li>
                                    <li><a class="dropdown-item text-dark" asp-controller="Graph" asp-action="Analytics">Analytics</a></li>
                                </ul>
                            </div>
                        </li>
                        <li class="drop-holder">
                            <div class="dropdown">
                                <a class="nav-link text-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    Test linh tinh
                                </a>
                                <ul class="dropdown-menu " aria-labelledby="dropdownMenuLink">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Rate" asp-action="Index">Rate</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TransData" asp-action="TransGce">TransGce</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="AutoComplete" asp-action="Index">AutoComplete</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="File" asp-action="Index">FileManager</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="MultiSelect" asp-action="Index">Multi-Select</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Drag" asp-action="Index">Drag</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Kanban" asp-action="Index">Kanban</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="PondFile" asp-action="Index">Pond File</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="FancyPhoto" asp-action="Index">FancyPhoto</a>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!--Serialize Object-->
    <script src="~/js/serializeobject/jquery.serializeobject.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <!--Rater-->
    <script src="~/js/rater/index.js"></script>
    <!--MultiSelect-->
    <script src="~/js/multiselect/jquery.multiselect.js"></script>
    <!--AutoComplete-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/corejs-typeahead/1.3.1/bloodhound.min.js"></script>

    <!--Muri Kanban-->
    <script src="https://cdn.jsdelivr.net/npm/muuri@0.9.5/dist/muuri.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/web-animations-js@2.3.2/web-animations.min.js"></script>

    <!--Summernote-->
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>